version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app
    command:
      - /bin/sh
      - -c
      - |
        cd /src &&
        npm install &&
        node app.js
    environment:
      - NODE_ENV=development

