version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    command:
      - /bin/sh
      - -c
      - |
        cd /app &&
        npm install &&
        node app.js
    environment:
      - NODE_ENV=development
    depends_on:
      - nginx
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./app:/app
